server:
  port: 8080

spring:
  application:
    name: jobscheduler-pro
  
  datasource:
    url: ${DB_URL:jdbc:h2:mem:jobscheduler}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
        format_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
  
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: ${MAIL_HOST:smtp.gmail.com}
        debug: false
    test-connection: false

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}

app:
  name: ${APP_NAME:JobScheduler Pro}
  version: ${APP_VERSION:1.0.0}
  
  kafka:
    topics:
      binary-jobs: ${KAFKA_TOPIC_BINARY:binary-jobs}
      email-jobs: ${KAFKA_TOPIC_EMAIL:email-jobs}
      job-status-updates: ${KAFKA_TOPIC_STATUS:job-status-updates}
    consumer:
      group-id: ${KAFKA_GROUP_ID:job-scheduler-group}
  
  minio:
    endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
    access-key: ${MINIO_ACCESS_KEY:minioadmin}
    secret-key: ${MINIO_SECRET_KEY:minioadmin}
  
  email:
    default-sender-name: ${EMAIL_SENDER_NAME:JobScheduler Pro}
    enabled: ${EMAIL_ENABLED:false}

logging:
  level:
    com.jobscheduler: ${LOG_LEVEL:INFO}
    org.springframework.kafka: WARN
    org.hibernate.SQL: WARN
    org.springframework.mail: WARN
    org.springframework.web: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true